Numpy is a library useful to work with numbers efficiently in python and specially with vectors, matrices, and tensors or arrays with >= 3 dimensions.

In [4]:
import numpy as np

scalar  = np.array(42)
scalar.ndim

0

In [6]:
import numpy as np

vector  = np.array([42,12,12])
vector.ndim

1

In [8]:
import numpy as np

matrix  = np.array([[42,12,12],[42,12,12]])
print(matrix)
matrix.ndim

[[42 12 12]
 [42 12 12]]


2

In [10]:
import numpy as np

tensor  = np.array([[[42,12,12],[42,12,12]],[[42,12,12],[42,12,12]], [[42,12,12],[42,12,12]]])
print(tensor)
tensor.ndim

[[[42 12 12]
  [42 12 12]]

 [[42 12 12]
  [42 12 12]]

 [[42 12 12]
  [42 12 12]]]


3

## Add or delete dimensions

In [15]:
vector = np.array([1,2,3,4,5], ndmin=0)
print(vector)
vector.ndim

[1 2 3 4 5]


1

### Add

In [18]:
expand = np.expand_dims(vector, axis=0)
expand

array([[1, 2, 3, 4, 5]])

#### Delete

In [17]:
vector  = np.squeeze(expand)
vector

array([1, 2, 3, 4, 5])